# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncLHwemTRdokRt3nUQUSaJUrKSlDZDpW
"""

import tensorflow as tf
import numpy as np

inputs = np.array([[3, 0, 0], [1, 2, 0], [1, 1, 1], [0, 0, 3]], dtype=float)
outputs = np.array([36, 32, 30, 30], dtype=float)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, activation='relu', input_shape=(3,)),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.1), loss='mean_squared_error')

model.fit(inputs, outputs, epochs=1000, verbose=False)

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de perdida")

test_data = np.array([[1,1,1]], dtype=float)
valor = model.predict(test_data)
print("Un cafe un jabon y una libra de arroz: "+ str(valor))